### ISSUE TITLE
Progressive JPEG

### ISSUE THREAD

**Issue by szepeviktor** [rflynn/imgmin#41]
Is it possible to convert to progressive JPEGs?

I think `convert -interlace JPEG after-imgmin.jpg output.jpg` will degrade quality.

**Comment by rflynn** [comment]
Thanks I will take a look

**Comment by szepeviktor** [comment]
Thank you.
I report v1.1 experiences.
Progressive JPEGs are also important for the visitors, they load nicely.

**Comment by szepeviktor** [comment]
Honestly I switched to https://github.com/danielgtaylor/jpeg-archive because you can select image comparision method an you have mozjpeg and the output is always progressive.
Please consider examining it.
