### ISSUE TITLE
packJPG

### ISSUE THREAD

**Issue by szepeviktor** [rflynn/imgmin#45]
Would imgmin benefit from - losslessly - pack-ing JPEG-s before or after?
http://packjpg.encode.ru/?page_id=17
code: https://github.com/szepeviktor/packJPG

**Comment by rflynn** [comment]
It appears that packJPG is a compression program that converts JPG <-> PJG; output in the form of PJG  files are not directly usable as JPG and require a decompression step. It seems this is handy as a content-aware plugin for general-purpose compression but does not give a usable image.

**Comment by szepeviktor** [comment]
Thank you for shading light on that.
I was looking only at file sizes, not the extentions.
